# Generated by Django 4.1.5 on 2023-01-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.DateField()),
                ('channel', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('utm_source', models.CharField(max_length=255)),
                ('utm_campaign', models.CharField(max_length=255)),
                ('utm_medium', models.CharField(max_length=255)),
                ('utm_term', models.CharField(max_length=255)),
                ('utm_content', models.CharField(max_length=255)),
                ('last_visit', models.DateField()),
            ],
        ),
    ]
