# Generated by Django 4.1.5 on 2023-01-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_users_botuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='registration',
            field=models.DateField(auto_now_add=True),
        ),
    ]
