# Generated by Django 4.1.5 on 2023-01-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_botuser_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
