# Generated by Django 4.1.5 on 2023-01-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_botuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
