# Generated by Django 4.1.5 on 2023-01-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_botuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='utm_content',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='utm_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='utm_term',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
