# Generated by Django 4.1.5 on 2023-01-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_botuser_email_alter_botuser_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed', models.CharField(max_length=255)),
                ('createdAt', models.CharField(max_length=255)),
                ('u_id', models.CharField(max_length=255)),
                ('channelName', models.CharField(max_length=255)),
                ('channelType', models.CharField(max_length=255)),
                ('cuid', models.CharField(max_length=255)),
                ('utmSource', models.CharField(max_length=255)),
                ('utmTerm', models.CharField(max_length=255)),
                ('utmContent', models.CharField(max_length=255)),
                ('utmCampaign', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('utmMedium', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
